### ISSUE TITLE
Pulling resizable content outside of container bounds causes incorrect internal content height

### ISSUE THREAD

**Issue by bswatson** [ericmann/gridster.js#1]
With a resizable content item, pulling the content outside of the lower container causes the item to snap back to it's minimum height.  This is expected, but it appears to only be visual in nature, as the sizey of the item is set to the full height of the gridster container minus row.  When adding a second content item, gridster places the item at the next row beyond that items sizey + row.

Once an item is put into this state, there is no way to resize or reduce the height of the content item.

Screenshot attached showing the resulting box.  White is the adjusted height content item and the shadow below represents the content item as gridster sees it.

![screen shot 2015-02-17 at 4 00 40 pm](https://cloud.githubusercontent.com/assets/303029/6237088/e9fafcd2-b6bd-11e4-8a2a-d7ce132d9192.png)

**Comment by ericmann** [comment]
This isn't an issue with Gridster, but with implementations of CSS in systems that use it. Essentially, the styles used in an implementation need to account for elements just as tall as the Gridster area itself.
